export const Urls={
SIGNIN_URL:'http://localhost:8095/users/signin',
SIGNUP_URL:'http://localhost:8095/users/signup',
addcontent:(id:number)=>`http://localhost:8095/courses/uploadcontent/${id}`,
UPLOAD_IMG: (userId: number) => `http://localhost:8095/users/upload/${userId}`,
addvideo: (id:number)=>`http://localhost:8095/courses/uploadvideo/${id}`,
loadCV: (userId: number) => `http://localhost:8095/users/uploadcv/${userId}`,
uploadimagetocourse:(courseid:number)=> `http://localhost:8095/courses/uploadimage/${courseid} `,
addpdftoassign:(courseid:number)=>`http://localhost:8095/Exams/uploadassignementdetail/${courseid}`,
chapters:'http://localhost:8095/courses/allchapters/${name}',
Downloadcv:'http://localhost:8095/users/getcv/${userId}',
getcourse:'http://localhost:8095/courses/getdetails/${name}',
ADDadmin:'http://localhost:8095/users/addadmin',
List_Countries:'http://localhost:8095/users/countries',
List_Roles:'http://localhost:8095/users/roles',
List_Speciality:'http://localhost:8095/users/specialities',
FORGET_PASSWORD: 'http://localhost:8095/users/reset_password/{{token}}/{{password}}',
RESET_PWD_Email:'http://localhost:8095/users/forgot_passworddemondByEmail/{{email}}',
ReclamationList:'http://localhost:8095/Reclamations/view',
UPDATE_PROFILE:'http://localhost:8095/users/update/${userId}',
Listusers:'http://localhost:8095/users',
Blockuser:'http://localhost:8095/users/block/${id}',
Unblockuser:' http://localhost:8095/users/unblock/${id}',
Deletereclam:'http://localhost:8095/Reclamations/delete/{{Id}}',
ListDemands:'http://localhost:8095/users/demandes',
Deleteuser:'http://localhost:8095/users/${iduser}',
Demandstatus:'http://localhost:8095/users/demandeforuser/${id}',
Deletedemand:'http://localhost:8095/users/deletedemande/${id}',
Deny:'http://localhost:8095/users/denydemande/${id}',
Accept:'http://localhost:8095/users/acceptdemande/${id}',
Domains:'http://localhost:8095/courses/domains',
Categ:'http://localhost:8095/courses/categories',
AddCourse:'http://localhost:8095/courses/add/${iduser}',
DeleteCourse:'http://localhost:8095/courses/delete/${Id}',
ViewCourses:'http://localhost:8095/courses/allcourses',
TutorCourses:'http://localhost:8095/courses/${IdUser}',
Enrollincourse:'http://localhost:8095/courses/enroll/${IdUser}/${idcourse}',
addassign:'http://localhost:8095/Exams/addassign/${idCourse}',
deleteassign:'http://localhost:8095/Exams/deleteassign/${id}',
getassign:'http://localhost:8095/Exams/assignement/${courseid}',
addcertif:'http://localhost:8095/Exams/addcertification/${ids}/${idc}',
generatecertif:'http://localhost:8095/Exams/generate-pdf/${certificationId}',
Viewstudentlist:'',
viewenrolledcourses:'http://localhost:8095/courses/coursesenrolledin/${IdUser}',
addreclam:'',
AddChapters:'http://localhost:8095/courses/addchapter/${courseId}',
DeleteChapters:'http://localhost:8095/courses/deletechapter/${chapterId}',
Totalnumberofparticipants:'http://localhost:8095/courses/totalnumber/${id}',
TotalRate:' http://localhost:8095/courses/totalr/${courseId}',
getcoursebyname:'http://localhost:8095/courses/getcourse/${name}',
getcourseimage:'http://localhost:8095/courses/export-image/${courseid}',




}